name: doc_app_sw
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.8.1 <4.0.0"


dependencies:

  flutter:
    sdk: flutter
  image_picker: ^1.1.2


  # iOS style icons
  cupertino_icons: ^1.0.8

  # Project dependencies
  dio: ^5.9.0
  equatable: ^2.0.5
  flutter_bloc: ^9.1.1
  flutter_svg: ^2.1.1
  flutter_screenutil: ^5.9.3
  flutter_native_splash: ^2.3.2
  shared_preferences: ^2.2.0
  skeletonizer: ^1.0.3

    # Firebase
  firebase_core: ^2.30.0
  cloud_firestore: ^4.15.0


dev_dependencies:
  build_runner: ^2.4.0
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/
    - assets/images/doctor1.png
